language: node_js
node_js:
  - 14

jobs:
  include:
    - script:
        - npm install
        - npm run build
        - npm run lint
    - script:
        - cd examples
        - npm install
        - npm run lint:ts
